# 应用服务 WEB 访问端口
spring.datasource.url=jdbc:mysql://localhost:3306/commentAnalysis
spring.datasource.username=root
spring.datasource.password=a334420a
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update  # ?????????
spring.jpa.show-sql=true  # ??SQL??????
spring.jpa.properties.hibernate.format_sql=true

# TensorFlow????
model.path=src/main/java/com/example/backend/model/comment_classifier/1